spring.application.name=umss-market-api

spring.datasource.url=jdbc:postgresql://localhost:5432/umss_market
spring.datasource.username=postgres
spring.datasource.password=Attendify2026!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

logging.level.org.springframework.security=DEBUG
ia.enabled=${IA_HABILITADA:true}

app.db.seed.enabled=false